version: '3'


services:
  pacientes:
    build: ./pacientes
    depends_on:
      - datapacientes
    environment:
      - PORT=2500
      - MONGODB_CNN=mongodb://datapacientes:27017/test
    # ports:
    #   - "2500:2500"
  platos:
    build: ./platos
    depends_on:
      - dataplatos
    environment:
      - PORT=2500
      - MONGODB_CNN=mongodb://dataplatos:27017/test
    # ports:
    #   - "2500:2500"
  registro:
    build: ./registro
    depends_on:
      - dataregistro
    environment:
      - PORT=2500
      - MONGODB_CNN=mongodb://dataregistro:27017/test
  datapacientes:
    image: mongo
    # ports:
    #   - "27017:27017"
  dataplatos:
    image: mongo
    # ports:
    #   - "27017:27017"
  dataregistro:
    image: mongo
    # ports:
    #   - "27017:27017"
  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pacientes
      - platos
      - registro