FROM node
COPY . /var/www
WORKDIR /var/www
RUN npm install
EXPOSE 2500
ENTRYPOINT [ "npm", "start" ]


# FROM node as Development

# FROM node as Testing
# COPY source dest --FROM Development

# FROM node as Production